path:
  # dataset: '${your_dataset_path}'
  # dataset: 'D:\workspace\repos\gitlab.com\ichiya\prcn2019-datasets\datasets\Images-20191014'
  dataset: './dataset/Images/'

  mistaken: './dataset/mistaken'
  model: './dataset'
  config: './dataset/config'
  log: './dataset/logs'
  gradcam: './dataset/GradCAM_results'

dataset:
  limit_size: -1
  test_size: 0.1
  extensions: ["jpg", "png", "jpeg"]

gradcam:
  # enabled: true
  enabled: false
  only_mistaken: true
  layer: "conv5"

network:
  height: 60
  width: 60
  channels: 3

  epoch: 10
  batch: 128
  subdivision: 4

  save_cycle: 0
  test_cycle: 1

  gpu_enabled: true
  # is_save_final_model: true
  is_save_final_model: false
  is_shuffle_dataset_per_epoch: true

option:
  is_show_network_difinition: true
  is_save_debug_log: true
  is_save_rate_log: true
  is_save_mistaken_pred: false
  is_save_used_image_path: true

  is_available_re_training: false
  re_training: false
  load_model_path: ""
